# Generated by Django 4.2.7 on 2023-12-09 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortUrls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_url', models.TextField()),
                ('short_url', models.CharField(max_length=10)),
                ('qr_file', models.ImageField(upload_to='/QrImages')),
                ('used', models.IntegerField()),
            ],
        ),
    ]
